### ISSUE TITLE
[ansible] userdata configuration is not setting the permissions correctly on files written to instance. 

### ISSUE THREAD

**Issue by davdunc** [davdunc/awscli-2-rpm#43]
[builder@ip-10-0-190-17 ~]$ ls -al 
ls -al 
total 0
drwxr-xr-x. 4 root    root    30 Feb  7 05:38 .
drwxr-xr-x. 3 root    root    21 Feb  7 05:38 ..
drwxr-xr-x. 2 root    root    20 Feb  7 05:38 .aws
drwx------. 2 builder builder 29 Feb  7 05:38 .ssh
[builder@ip-10-0-190-17 ~]$ sudo chown -R builder:builder .aws
sudo chown -R builder:builder .aws

**Comment by davdunc** [comment]
I expected the userdata configuration to include setting the permissions correctly on the file. 

offending section: 
``` yaml
write_files:
- encoding: b64
  content: W2RlZmF1bHRdCnJlZ2lvbiA9IHVzLXdlc3QtMgpvdXRwdXQgPSBqc29uCg==
  owner: builder:builder
  path: /home/builder/.aws/config
  permissions: '0640'
```
